[build]
        command = "npm run build"
        functions = "functions"
        publish = "dist"

[dev]
        framework = "#custom"
        command = "npm run dev:webpack"
        targetPort = 8080
        port = 8090
        publish = "dist"
        autoLaunch = false
